version: '3.4'
networks:
  my-mongo-cluster:
services:
  mongo1:
    container_name: mongo1
    image: mongo
    networks:
      - my-mongo-cluster
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
    - 30001:27017
    volumes:
      - ./mongo-keyfile:/data/mongo-keyfile
    command: "--bind_ip_all --replSet my-mongo-set --keyFile data/mongo-keyfile"
  mongo2:
    container_name: mongo2
    image: mongo
    networks:
      - my-mongo-cluster
    ports:
    - 30002:27017
    volumes:
      - ./mongo-keyfile:/data/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    command: "--bind_ip_all --replSet my-mongo-set --keyFile data/mongo-keyfile"
  mongo3:
    container_name: mongo3
    image: mongo
    networks:
      - my-mongo-cluster
    ports:
    - 30003:27017
    volumes:
    - ./mongo-keyfile:/data/mongo-keyfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pwd
    command: "--bind_ip_all --replSet my-mongo-set --keyFile data/mongo-keyfile"